### ISSUE TITLE
Evaluate error

### ISSUE THREAD

**Issue by shuyansy** [md-mohaiminul/VideoRecap#3]
I have met an issue like this： 
Is there any ways to solve that? thanks!
Loading Video encoder from pretrained_models/clip_openai_timesformer_base.baseline.ep_0003.pth
Traceback (most recent call last):
  File "eval_unified.py", line 244, in <module>
    main(args)
  File "eval_unified.py", line 53, in main
    model = VideoRecap(old_args, use_vision_model_forced=True)
  File "/mnt/hpfs/baaidcai/shuyan/VideoRecap-master/src/models/video_recap.py", line 86, in __init__
    vision_model.load_state_dict(state_dict, strict=True) 
  File "/home/baaidcai/anaconda3/envs/videorecap/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SpaceTimeTransformer:
        size mismatch for temporal_embed: copying a param with shape torch.Size([1, 4, 768]) from checkpoint, the shape in current model is torch.Size([1, 512, 768]).

**Comment by md-mohaiminul** [comment]
Hi,
Thanks for reaching out. The issue is now solved and the evaluation script is updated accordingly. Could you please try with the updated code?
